name: Build LaTeX document
on: 
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            tlmgr update --self && tlmgr update --all
            apk add make
            make all 
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v2
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          private-key-name: github_ci
        continue-on-error: true # In case key-auth fails
      - name: Clone and push repository
        run: |
            git clone git@github.com:Siddhant-Ray/siddhant-ray.github.io.git temp
            cp cv.pdf ./temp/assets/pdf
            cd ./temp
            git add .
            git diff-index --quiet HEAD || git commit -m "Automatic updation of cv from https://github.com/Siddhant-Ray/Curriculum-Vitae"
            git push origin master
        continue-on-error: true # In case push fails
      - name: Delete placeholder release
        uses: actions/github-script@v6
        continue-on-error: true # in case there's no existing release
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo } = context.repo
            const { data: { id } } = await github.rest.repos.getLatestRelease({ owner, repo })
            await github.rest.repos.deleteRelease({ owner, repo, release_id: id })
      - name: Delete release tag
        run: |
          git push --delete origin release
        continue-on-error: true # in case there's no existing release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          body: "Placeholder release for the latest build "
          name: Latest
          tag_name: release
          files: |
            cv.pdf
            resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
